#!/bin/sh
#simple script to remaster the puppy live-cd.
#(c) Copyright 2006 Barry Kauler, www.puppyos.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#BK 9 oct 2007: updated for puppy v3.01.
#RE 9 apr 2008: v3.99 copy active post-install scripts
#v4.02 /lib/modules/firmware.dep.<kern>,DOTconfig-K<kern> moved to /etc/modules. ...um no mods this script.
#v411 update what gets copied from /root and /etc.
#v412 /etc/DISTRO_SPECS, renamed pup_xxx.sfs, pup_save.2fs etc.
#w001 pup files renamed to woof-555.sfs, woofsave.2fs (or similar).
#w018 april 2009: Woof-related fixes, new standardised package database format.
#w460 zdrv has new name format, ex zu500269.sfs.
# 22jun09 by Masaki Shinomiya <shino@pos.to> bugfix in cd drive selection
# 23jun09 I18N
# 27jun09 copy all *.msg and *.16 from Live CD
# 01jul09 needed space calculation
# 02jul09 I18N bugfix to burn CD
# 08jul09 remove kernel modules from initrd
# 08jul09 loop mounted iso file usable
# 7aug09 grub4dos support
#w482 shinobar: exclude /lib/modules/${KERNELVER}/initrd.
#v423 bugfix.
# 2oct09 v430JPRC shinobar: make ZDRVSFS
#v431 bugfixes.
#v431JP add application ID on iso image.(removed)
#v431JP removed app ID code, permitions of sfs files, forground collor of rxvt
#v431JP mkisofs with Joliet option, volume id, what copied from cd, remove slmodems
#v431JP error message for full install
#091212 weird bug, no processes but when run this, x restarts...
# 28dec09 remove /modules/${KERNELVER}/modules.*
#100117 save user-modified rox globicons file.
# 20jan10 Puppy v4.x(before woof) backward compatibility
#100913 simplified puppy filenames. see variables in /etc/DISTRO_SPECS.
#100916 no longer have DISTRO_DEVXSFS in /etc/DISTRO_SPECS.(it was only there briefly)
#101020 no longer have /etc/modprobe.conf.
#101107 bug fix from zygo.
#110505 support sudo for non-root user.
#110722 tweak sort.
#110808 PANZERKOPF: bug fix. 110822 reverted.
#110902 rodin.s bug fix.
#120323 replace 'xmessage' with 'pupmessage'.
#120329 Xdialog bug --yesno supposed to "yes" "No" buttons, but they are "OK" "Cancel".
#120512 01micko: support xz compression.
#120605 rerwin: omit /dev/snd content, /dev/.udev subdirectory and modem daemons from new master (because daemons reinstalled from firmware if needed).
#120606 rerwin: support users' replacement of stripped /root & /etc with complete directories (for "boot disk"). 
#120607 rerwin: Remove indicators/files for integrated user-installed packages.
#120628 shinobar: no change id-string for reuse
#120705 shinobar: dummy 'pupmessage'
#120721 avoid wildcards option introduded in 120605 (thanks to majorfoo ), remove /usr/share/icons/hicolor/icon-theme.cache

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

Yes_lbl="Yes"
No_lbl="No"

# remasterpup2.mo
m_01="Puppy simple CD remaster"
m_02="ERROR"
m_03="This program requires a \$PUPPYSFS file mounted on /initrd\${PUP_LAYER}.\n
Which is not the case here, probably because this is a full hard drive
installation?\n
Whatever, boot Puppy from live-CD and then you will be able to
use this script.
\n\n
Note, I have not tried it, but if you setup the situation of \$PUPPYSFS\n
mounted on directory /initrd\${PUP_LAYER}, that will be acceptable for this program.\n
You will also need a current live-CD, as the program gets files off it.\n
Anyone want to try it?
\n\n
Click 'Ok' button to quit..." 
#m_04 skipped
m_05="Welcome! This little program takes a snapshot of your current system and burns it to CD.
\n\n
A Puppy live-CD has 4 main files: vmlinuz, isolinux.cfg, initrd.gz and \$PUPPYSFS. Note, in some builds of Puppy there may also be a 5th file, \${ZDRVSFS}.
\n\n
It is \$PUPPYSFS that mainly interests us here: it has the entire Puppy filesystem, everything from '/' down. What this script does is rebuild this file \$PUPPYSFS, with everything currently under '/' -- that is, all user-installed packages, all mounted .sfs extension files, everything, gets combined into one file, \$PUPPYSFS and burnt to CD.
Note, if you have an 'underdog Linux' mounted, that too will get combined into the \$PUPPYSFS file, so beware, it could get big!
\n\n
Click OK button to continue (or close window to quit)..."
m_06="Calculating needed working space.\nPlease wait, this may take awhile..."
m_07="currently mounted"
m_08="not mounted"
m_09="Filesystem"
m_10="Size"
m_11="Free"
m_12="Note 2: you can use the tmpfs ramdisk, which is in RAM, if it has enough space."
m_13="A working area is required in which to create the new live-CD iso file.\n
Here are the available partitions. You must choose one that has at least \${SIZENEEDEDM}M free space on it. Also, if you choose to create an ISO file rather than burn direct to CD/DVD, then you will need an extra 100 - 200MB space (whatever the size of ISO file is going to be).
\n\n
If the partition that you would like to use has less than \${SIZENEEDEDM}M free space on it, you will need to quit this script and delete some files.
\nNote 1: you can use a usb drive, but it needs to have been plugged in before
        running this script, so that it will get detected.\n
\${TMPFSMSG}\n
Highlight desired choice then click OK button..."
m_14="This remaster program needs to read some files off the current live-CD.\n
You can also use a .iso file if it is already mounted as a virtual CD."
m_14_1="Choose the CD/DVD drive..."
m_14_2="NO CD/DVD drives found."
m_15="Mounted CD, get rid of it before running this program!" 
m_16="Please insert the current Puppy live-CD into drive \$BURNERDRV.\n
Then click OK..."
m_16_1="Do you like to make \$ZDRVSFS, the separate driver file?"
m_17="Copying files from CD to \$WKGMNTPT/puppylivecdbuild/, please wait..."
m_18="Creating the \$PUPPYSFS file in \$WKGMNTPT/puppylivecdbuild/.\n
This can take quite a long time, so please wait.... and wait...\n
This window will disappear when \$PUPPYSFS is finally created.\n
Please wait..."
m_19="This program has created folder /tmp/root, which has everything that is now
going to be added as /root in the \$PUPPYSFS file.\n
This is mostly 'pristine', as obviously you do not want all your cache files,
temp files, email files, and other working/temporary files to be burnt onto
the CD. However, if you are familiar with the workings of Puppy, you might
like to take a look at /tmp/root right now, and possibly add anything that
you want from /root (or remove something!)\n
(if you think that this program has missed out something important that
 should be burnt into /root on the CD, please let me know -- Barry Kauler)
\n\n
After examining /tmp/root,\n
click 'Ok' to add /root in \$PUPPYSFS file..."
m_20="Hardware customisation was not chosen."
m_21="Have created the /etc directory for the new \$PUPPYSFS file.\n
It is in a 'pristine' state, but you can choose to customise it.\n
Do you want to add customisations for your hardware? Examples are
mouse, keyboard, video. But, if you answer 'Yes' here, the live-CD
will be preconfigured for your PC only. Therefore, it is best to
answer 'No' if you want to boot the new live-CD on different PCs.
\n\n
Click 'Yes' button to customise /etc...
Click 'No' button not to customise (recommended)..."
m_22="These files were customised in /etc:\n
codepage fontmap keyboardtype keymap mousebuttons mousedevice videomode
eth0mode eth1mode resolv.conf localtime TZ cdburnerdevice dvddevice modemdevice
securetelnetrc modprobe.d/* rdesktoprc windowmanager xextraoptions X11/xorg.conf
and directory network-wizard."
m_23="\$MSG1
\n\n
If you know what you are doing, you can now modify any files in /tmp/etc
folder. This is just about to be added to /etc in the .sfs file.\n
Do anything you want before clicking 'Ok'.\n
(If this program has missed something important, let me know -- Barry Kauler)
\n\n
Click 'Ok' to add /etc in \$PUPPYSFS file..."
m_24="Almost ready to burn the CD!\n
All the files that will be burnt to CD are in \$WKGMNTPT/puppylivecdbuild/.
\n\n
The thing that you may want to do is edit isolinux.cfg. It has this:\n
\$ISOLINUXCFG
\n\n
'pmedia' parameter is a hint to Puppy what media you are booting Puppy from.\n
'pmedia=cd' means any CD/DVD drive. Other options are:\n
 usbflash usbhd usbcd ataflash atahd atacd atazip scsihd scsicd
 (where 'ata' means either IDE or SATA interface, i.e. an internal drive)
\n\n
'pkeys' is the default keyboard layout. Example: 'pkeys=us'  Choices are:\n
 azerty be-latin1 br-abnt2 br-abnt br-latin1-abnt2 br-latin1-us by cf croat cz de\n
 de-latin1 dk dvorak dvorak-l dvorak-r es et fi fr gr hu101 hu il it jp106 lt mk\n
 nl no pl pt-latin1 ro ru se sg sk-qwerty sk-qwertz slovene sv-latin1 uk us wangbe
\n\n
You may also add any kernel parameters. Some PCs require 'acpi=off' to boot properly.
\n\n
(If answer 'Yes', an editor will appear, must exit
 editor before this program will continue)\n
Click 'Yes' button to edit isolinux.cfg..."
m_25="Almost ready to burn the CD!\n
All the files that will be burnt to CD are in \$WKGMNTPT/puppylivecdbuild/.
\n\n
If you want to add any more files, say extra SFS files, or to edit or modify the
files in any way, do it now. Note, if you add an extra SFS file, say 'devx.sfs'
then it will be available for use when you boot the new live-CD.
\n\n
If you want to make any changes, use ROX-Filer to open \$WKGMNTPT/puppylivecdbuild/
and do so now, before clicking the OK button."
m_25_1="No boot loaders found. You need isolinux.bin or grldr to make bootable CD.\nClick 'OK' to quit.(leaving \$WKGMNTPT/puppylivecdbuild/ files in existence)"
m_26="All the files that will be burnt to CD/DVD are in \$WKGMNTPT/puppylivecdbuild/.
\n\n
As the working partition may have limited space (for example, you are using a USB pen drive), these files are burnt direct to CD/DVD, rather than create an intermediary iso file. If you do need an iso file, you can copy it from the CD afterward (dd if=/dev/\$BURNERDRV of=puppy.iso seek=0 bs=32k).
\n\n
However, if you just want to create an iso file now and not burn to CD/DVD, click the 'No' button.
\n\n
Click 'No' button (or close-box on window) to quit program at this point (leaving  \$WKGMNTPT/puppylivecdbuild/ files in existence), and further option to create an iso file...\n
Click 'Yes' button to burn to CD/DVD..."
m_27="Click 'Yes' button to create a 'custom-puppy.iso' in \${WKGMNTPT}/ (assuming that there is 100MB-200MB free space)...\n
Click 'No' button (or close-box on window) to quit program at this point (leaving  \${WKGMNTPT}/puppylivecdbuild/ files in existence)..."
m_27_1="You can add the CD volume ID,
it can be used on Windows and on some Linux system."
m_28_1="\$WKGMNTPT/custom-puppy.iso created."
m_28_2="ISO files not created."
m_28="\$WKGMNTPT/puppylivecdbuild/ files left in existence.\n
Click 'Ok' button to quit..."
m_29="Please choose the media to burn to.\n
The burner drive is /dev/\$BURNERDRV, and obviously it must be able to burn a DVD if you want to burn a DVD!
\n\n
Note, you can later use the 'dd' program to create an iso file:\n
 # dd if=/dev/\$BURNERDRV of=puppy.iso seek=0 bs=32k
\n\n
PLEASE INSERT THE NEW CD OR DVD RIGHT NOW, THEN CHOOSE FROM MENU..."
m_30="New blank recordable CD"
m_31="New blank DVD-R (not +R, -RW, +RW)"
m_32="Finished. Press ENTER key to continue"
m_33="You should now have a new custom Puppy live-CD!
\n\n
WARNING:\n
There is a tricky situation here, as all the installed packages (plus anything else that you may have installed, such as loaded .sfs extension files, have all been burnt to CD/DVD).
But, they are still installed in the current \${DISTRO_FILE_PREFIX}save.2fs, the Puppy persistent storage file (where all your stuff gets saved, so it is there next time Puppy is booted). All those files are duplicated, but will that do any harm if you boot the new CD? ...should be okay, but I recommend that you uninstall as much as possible right now, before booting the new CD. Note, do not uninstall them after booting the new CD as that will also 'delete' the packages burnt onto the CD.
\n\n
Or, easiest and cleanest option, boot Puppy with 'pfix=ram' boot parameter then at shutdown create a brand new '${DISTRO_FILE_PREFIX}save' file. In fact, this is the wisest thing to do regardless, as you don't even know if the custom CD is going to work properly -- so it is best to bootup in ram only to find out!"
m_34="You need to choose a burner drive so that the files created by this program can be burnt to a new CD/DVD."
m_35="\$SFSPATH found.\nDo you reuse it without any change?"
# end of remasterpup2.mo

# I18N
# set locale
# myLOCALE=$LANG # is enough for puppy. but this code is more general. 
for myLOCALE in C $(echo $LANGUAGE|cut -d':' -f1) $LC_ALL $LANG;do :;done	# ex. 	ja_JP.UTF-8
# search locale file
myLOCALE1=$(echo $myLOCALE|cut -d'.' -f1)		# ex.	ja_JP
myLOCALE2=$(echo $myLOCALE|cut -d'_' -f1)	# ex.	ja
LOCALEDIR=/usr/share/locale
LOCALEFILE=$(basename $0).mo
for D in C $myLOCALE2 $myLOCALE1 $myLOCALE
do
	F="$LOCALEDIR/$D/LC_MESSAGES/$LOCALEFILE"
	[ -f "$F" ] && . "$F" 
done
# end of I18N

#120705 shinobar: dummy 'pupmessage'
pupmessage() {
  for p in pupmessage gxmessage xmessage; do
    XMESSAGE=$(which $P) && break
  done
  $XMESSAGE "$@"
}

choice_cdd () {
#copy files off live-cd.... w018 use probedisk2...
#DRIVESFND="`probedisk2 2>&1`"
#IDEDRVSFND="`test-eide 2>&1 | grep "cdrom"`"
SELECTIONS="`probedisk2 2>&1 | grep '^/dev/' | grep "|optical|" | cut -f 1,3 -d "|" | tr " " "_" | tr "|" " " | tr '$' "_"`"
#zSELECTIONS="`echo "$SELECTIONS" | tr '\n' ' '`" #v431 bugfix. # shinobar: need not for this code
SELECTIONS="$SELECTIONS $VIRTUALCD"
if [ "$(echo "$SELECTIONS"|tr -d ' ')" = "" ]; then
	Xdialog --wrap --left --title "$m_01: $m_02" --msgbox "$m_14_2
$MSG" 0 0
	exit
fi
DIALOG="Xdialog --wrap --left --title \"$m_01\" --stdout --menubox \"$MSG\n\n$m_14_1\" 0 48 4 $SELECTIONS 2> /dev/null"
BURNERDRV=""
RESULT=$(eval $DIALOG) #w018	# 22jun09
[ $? -ne 0 ] && exit
BURNERDRV=$RESULT
[ "$BURNERDRV" = "" ] && exit
BURNERDRV="`echo -n "$BURNERDRV" | cut -f 3 -d '/'`"
}

LANG=C #faster, plus Xdialog happier.
KERNELVER="`uname -r`"

#120512 01micko: set compression
COMP=""
mksquashfs -help &>/tmp/mk #refuses to grep from stdout
grep 'xz' /tmp/mk &>/dev/null
[ "$?" = "0" ] && COMP="-comp xz"
ARCH="`uname -m`"
[ "$(uname -m|grep ^i)" ] && ARCH="`uname -m|cut -c3,4`"
case "$ARCH" in
86)AOPT="-Xbcj x86" ;;
*)AOPT="" ;; #todo add other arches
esac
rm /tmp/mk
COPTIONS=""${COMP}" "${AOPT}""
#end set compression

#variables created at bootup by /initrd/usr/sbin/init...
. /etc/rc.d/PUPSTATE
[ "$PUP_LAYER" = "" ] && PUP_LAYER="/pup_ro2"

. /etc/DISTRO_SPECS
if [ ! "$DISTRO_IDSTRING" ];then #101107
  #need some stuff in here if want to support older puppies. maybe also more fixes needed further down.
 pupmessage -bg red -title "RemasterPup" -center "Sorry, your Puppy is too old for this script"
 exit
else
 PUPPYSFS="$DISTRO_PUPPYSFS" #ex: puppy.sfs
 ZDRVSFS="$DISTRO_ZDRVSFS"   #ex: zdrv.sfs
 #DEVXSFS="$DISTRO_DEVXSFS"   #ex: devx.sfs
 SFSBASE="`basename $PUPPYSFS .sfs`" #ex: puppy
fi

#100913 generate a new id-string...
IDDATE="`date +%y%m%d%H%M%S`" #12 bytes, ex: 100911153319
IDPREFIX="`echo -n "$DISTRO_FILE_PREFIX" | cut -b 1`"
#vDISTRO_VERSION="`echo -n "$DISTRO_VERSION" | cut -b 1-3`" #in case it ever gets bigger than 3 chars.
#IDSTRING="${IDPREFIX}${vDISTRO_VERSION}${IDDATE}"
#...needs to be appended to vmlinuz, puppy.sfs, zdrv.sfs and devx.sfs
#110422 increase size of idstring to 32 bytes...
IDSTRING="${IDPREFIX}${IDDATE}ZZZZ${DISTRO_VERSION}"
#...ZZZZ reserved space for future use.
LEN1=`echo -n "$IDSTRING" | wc -c`
LEN2=`expr 32 - $LEN1`
EXTX=''
while [ $LEN2 -gt 0 ];do
 LEN2=`expr $LEN2 - 1`
 EXTX="${EXTX}X"
done
IDSTRING="${IDSTRING}${EXTX}" #32 bytes ex: w110423092024ZZZZ5.1.2XXXXXXXXXX

PPATTERN="/initrd${PUP_LAYER}"
if [ "`mount | grep "$PPATTERN"`" = "" ];then
 #no puppy.sfs file mounted on pup_ro2, probably h.d. install...
 eval m_03=\"$m_03\"
 Xdialog --wrap --left --title "$m_01: $m_02" --msgbox "$m_03" 0 0
 exit
fi

SAVEPART="$PDEV1" #from PUPSTATE.
CDR="/dev/$SAVEPART"

#choose where to create isolinux-builds/ directory...
eval m_05=\"$m_05\"
Xdialog --wrap --left --title "$m_01" --msgbox "$m_05" 0 0

[ ! $? -eq 0 ] && exit

#calc size needed...
Xdialog --wrap --left  --title "$m_01" --no-buttons --ignore-eof  --infobox "$m_06" 0 0 0 &
XPID=$!
SIZEOPT=0
SIZEBIN=`du -sk /bin | cut -f 1`
SIZESBIN=`du -sk /sbin | cut -f 1`
SIZELIB=`du -sk /lib | cut -f 1`
SIZEUSR=`du -sk /usr | cut -f 1`
SIZEOPT=0	# 01jul09
[ -d /opt ] && SIZEOPT=`du -sk /opt | cut -f 1`
sync
#kill $XPID
#SIZETOTALK=`expr $SIZEBIN + $SIZESBIN + $SIZELIB + $SIZEUSR + $SIZEOPT`
#SIZETOTALM=`expr $SIZETOTALK \/ 1024`
SIZETOTALK=`dc $SIZEBIN $SIZESBIN + $SIZELIB + $SIZEUSR + $SIZEOPT + p`
SIZETOTALM=`dc $SIZETOTALK 1024 \/ p| cut -d'.' -f1`	# 01jul09
[ "$SIZETOTALM" ] || SIZETOTALM=1
#echo "SIZETOTALM=$SIZETOTALM"
#estimate a compressed size...
SIZENEEDEDM=`expr $SIZETOTALM \/ 3`
SIZESLACKM=`expr $SIZENEEDEDM \/ 3` #guess
SIZENEEDEDM=`expr $SIZENEEDEDM + $SIZESLACKM`
SIZENEEDEDM=`expr $SIZENEEDEDM + 25` #space for vmlinuz, initrd.gz, zdrv, etc
#echo "SIZENEEDEDM=$SIZENEEDEDM"
#now choose working partition... v431 add ext4...
PARTSLIST="`probepart -m 2> /dev/null | grep '^/dev/' | grep -E 'ext2|ext3|ext4|reiserfs|msdos|vfat|ntfs' | cut -f 1-3 -d '|'`"

 echo -n "" > /tmp/schoices.txt
 echo "$PARTSLIST" |
 while read APART
 do
  [ "$APART" = "" ] && continue #v3.01 preaution
  MNTSTATUS="($m_07)"
  ATAG="`echo -n "$APART" | cut -f 1 -d '|' | cut -f 3 -d '/'`"
  ASIZE="`echo -n "$APART" | cut -f 3 -d '|'`"
  AFS="`echo -n "$APART" | cut -f 2 -d '|'`"
  AFPATTERN="^/dev/$ATAG " #v3.01
  AFREE="`df -m | grep "$AFPATTERN" | tr -s " " | cut -f 4 -d " "`"
  FLAG_RO='no' #v431
  if [ ! "$AFREE" ];then
   MNTSTATUS="($m_08)"
   mkdir -p /mnt/$ATAG
   mount -t $AFS /dev/$ATAG /mnt/$ATAG > /dev/null 2>&1
   if [ $? -eq 0 ];then
    if [ "$ATAG" = "fd0" ];then
     FFREE=`df -k | grep "$AFPATTERN" | tr -s " " | cut -f 4 -d " "`
     AFREE="`dc $FFREE 1024 \/ p`"
    else
     AFREE="`df -m | grep "$AFPATTERN" | tr -s " " | cut -f 4 -d " "`"
    fi
    [ "`mount | grep "$AFPATTERN" | grep ' (rw'`" = "" ] && FLAG_RO='yes' #v431 make sure writable.
    umount /dev/$ATAG
   else #v431
    continue
   fi
  else
   [ "`mount | grep "$AFPATTERN" | grep ' (rw'`" = "" ] && FLAG_RO='yes' #v431 make sure writable.
  fi
  [ "$FLAG_RO" = "yes" ] && continue #v431
  [ "$AFS" ] && echo "${ATAG} \"Filesystem: $AFS  Size: ${ASIZE}M  Free: ${AFREE}M ${MNTSTATUS}\" \\" >> /tmp/schoices.txt #v3.01 added precaution.
 done
 SCHOICES="`cat /tmp/schoices.txt`"

#add tmpfs ramdisk choice...
SIZETMPFSM="`df -m | grep '^tmpfs' | grep '/initrd/pup_rw' | tr -s " " | cut -f 4 -d " "`"
TMPFSMSG=''
if [ "$SIZETMPFSM" != "" ];then
 TOTALTMPFSM="`df -m | grep '^tmpfs' | grep '/initrd/pup_rw' | tr -s " " | cut -f 2 -d " "`"
 if [ "$SCHOICES" = "" ];then #v3.01
  SCHOICES="ramdisk \"$m_09: tmpfs  $m_10: ${TOTALTMPFSM}M  $m_11: ${SIZETMPFSM}M ($m_07)\" \\"
 else
  SCHOICES="$SCHOICES
ramdisk \"$m_09: tmpfs  $m_10: ${TOTALTMPFSM}M  $m_11: ${SIZETMPFSM}M ($m_07)\" \\"
 fi
 TMPFSMSG="$m_12
 "
fi

[ "$SCHOICES" = "" ] && exit #precaution.
 eval m_13=\"$m_13\"
 echo '#!/bin/sh' > /tmp/savedlg
 echo -n "Xdialog --wrap --left --stdout --title \"$m_01\" --menubox \"$m_13\" 0 0 5 " >> /tmp/savedlg
 echo "$SCHOICES"  >> /tmp/savedlg
 echo ' > /tmp/tag.txt' >> /tmp/savedlg
 chmod 755 /tmp/savedlg

kill $XPID
/tmp/savedlg
WKGPART="`cat /tmp/tag.txt`"
echo "WKGPART=$WKGPART"
[ "$WKGPART" = "" ] && exit
#[ "$WKGPART" = "ramdisk" ] && WKGPART="tmpfs"

#now get the files off it...
#firstly need working place to write to...
[ "$WKGPART" = "ramdisk" ] && WKGMNTPT="/"
WPATTERN="/dev/$WKGPART "
[ "$WKGMNTPT" = "" ] && WKGMNTPT="`mount | grep "$WPATTERN" | tr -s " " | cut -f 3 -d " "`"
#[ "$WKGMNTPT" = "/initrd/pup_rw" ] && WKGMNTPT="/"
if [ "$WKGMNTPT" = "" ];then
 PPATTERN="^$WKGPART "
 WKGFS="`echo "$SCHOICES" | grep "$PPATTERN" | cut -f 2 -d ':' | cut -f 2 -d " "`"
 [ "$WKGFS" = "msdos" ] && WKGFS="vfat"
 mkdir -p /mnt/$WKGPART
 mount -t $WKGFS /dev/$WKGPART /mnt/$WKGPART
 [ $? -ne 0 ] && exit #precaution.
 WKGMNTPT="/mnt/$WKGPART"
fi
[ "$WKGMNTPT" = "/" ] && WKGMNTPT=""

# reuse if sfs file already exists
NEW="yes"
SFSPATH=$(ls -1 $WKGMNTPT/puppylivecdbuild/$PUPPYSFS 2>/dev/null)
if [ "$SFSPATH" != "" -a $(echo "$SFSPATH" | wc -l) -eq 1 ]; then
	eval m_35=\"$m_35\"
	Xdialog --wrap --left --title "$m_01" --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$m_35" 0 0 && NEW="no"
fi
SFSPATH=""

if [ "$NEW" = "yes" ]; then  ###### long skip if, cleating new sfs

#VIRTUALCD=$(mount -t iso9660|grep '^/dev/loop' | sed -e 's/on[ ].*+//' -e 's/[ ]type[ ]iso9660[ ].*$//')
#VIRTUALCD="`grep -E "loop.*iso9660" /proc/mounts | cut -f 1-2 -d ' ' | tr '\n' ' '`" #110808 PANZERKOPF bug fix. 110822 reverted.
VIRTUALCD=$(grep -E "loop.*iso9660" /proc/mounts | grep '^/dev/loop'| cut -d' ' -f1,2 | sed -e 's%/mnt.*+%%') #110902 rodin.s bug fix.
MSG="$m_14"
choice_cdd

CDPATTERN="/dev/$BURNERDRV "
CDMNTPT="`mount | grep "$CDPATTERN" | tr -s " " | cut -f 3 -d " "`"
if [ "$CDMNTPT" != "" ];then
 if [ ! -f $CDMNTPT/initrd.gz ];then
  #091212 weird bug, no processes but when run this, x restarts...
  xFUSER="`fuser -m /dev/$BURNERDRV 2>/dev/null`" #do this first, seems to fix it.
  [ "$xFUSER" != "" ] && fuser -k -m /dev/$BURNERDRV
  sync
  umount /dev/$BURNERDRV 2> /dev/null
  if [ $? -ne 0 ];then
   Xdialog --wrap --left  --title "$m_02" --msgbox "$m_15" 0 0
   exit
  fi
  CDMNTPT=""
 fi
fi

if [ "$CDMNTPT" = "" ];then
 eval m_16=\"$m_16\"
 while [ 1 ];do
 Xdialog --wrap --left  --title "$m_01" --msgbox "$m_16" 0 0
 [ $? -eq 0  ] || exit	# 22jun09
 #now mount it...
 CDMNTPT="/mnt/$BURNERDRV"
 mkdir -p /mnt/$BURNERDRV
 mount -t iso9660 /dev/$BURNERDRV /mnt/$BURNERDRV
 [ $? -eq 0 ] && break
 done
fi

eval m_16_1=\"$m_16_1\"
Xdialog --wrap --left  --title "$m_01" --default-no --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$m_16_1" 0 0
[ $? -eq 0 ] && MKZDRV="yes" || MKZDRV=""

#now get the files off it...
#firstly need working place to write to...
[ "$WKGPART" = "ramdisk" ] && WKGMNTPT="/"
WPATTERN="/dev/$WKGPART "
[ "$WKGMNTPT" = "" ] && WKGMNTPT="`mount | grep "$WPATTERN" | tr -s " " | cut -f 3 -d " "`"
#[ "$WKGMNTPT" = "/initrd/pup_rw" ] && WKGMNTPT="/"
if [ "$WKGMNTPT" = "" ];then
 PPATTERN="^$WKGPART "
 WKGFS="`echo "$SCHOICES" | grep "$PPATTERN" | cut -f 2 -d ':' | cut -f 2 -d " "`"
 [ "$WKGFS" = "msdos" ] && WKGFS="vfat"
 mkdir -p /mnt/$WKGPART
 mount -t $WKGFS /dev/$WKGPART /mnt/$WKGPART
 [ $? -ne 0 ] && exit #precaution.
 WKGMNTPT="/mnt/$WKGPART"
fi
[ "$WKGMNTPT" = "/" ] && WKGMNTPT=""

eval m_17=\"$m_17\"
Xdialog --wrap --left  --title "$m_01" --no-buttons --ignore-eof   --infobox "$m_17" 0 0 0 &
XPID=$!
rm -rf $WKGMNTPT/puppylivecdbuild #precaution
mkdir $WKGMNTPT/puppylivecdbuild
#now copy the files... # v431JP HTM, ICO, INF
   sync
   for F in vmlinuz initrd.gz ${ZDRVSFS} grldr menu.lst '*.xpm' isolinux.bin isolinux.cfg '*.msg' '*.16' '*.HTM*' '*.ICO' '*.INF'
   do
	cp $CDMNTPT/$F $WKGMNTPT/puppylivecdbuild/ 2> /dev/null
	sync
   done
umount /dev/$BURNERDRV 2> /dev/null

kill $XPID
eval m_18=\"$m_18\"
Xdialog --wrap --left  --title "$m_01" --no-buttons --ignore-eof   --infobox "$m_18" 0 0 0 &
XPID=$!

#create new puppy.sfs file...
squash() {
	echo $0 $@
	rxvt -bg orange -fg black -title "$m_01" -geometry 80x6 -e mksquashfs $@
}
DIRHOME=""
[ -d /home ] && DIRHOME="/home"
[ -d /sys ] && DIRSYS="/sys"
[ -d /lost+found ] && DIRLOST="/lost+found"
rm -f ${WKGMNTPT}/puppylivecdbuild/$PUPPYSFS 2> /dev/null
sync
#note, /puppy.sfs is not normally there, i relocated it to a separate tmpfs,
#however have not yet done that for multisession-cd/dvd (PUPMODE=77).
#note, /home could be in underdog linux...

# modules copied from initrd
ANOTHER_REMOVE="/lib/modules/$KERNELVER/initrd /lib/modules/*/modules.*"	# 28dec09 modules.*
if [ "$MKZDRV" = "yes" ]; then
  rm -f $WKGMNTPT/puppylivecdbuild/$ZDRVSFS 
  mksquashfs /lib $WKGMNTPT/puppylivecdbuild/$ZDRVSFS -keep-as-directory -e /lib/[^m]* $ANOTHER_REMOVE
  ANOTHER_REMOVE="/lib/modules"
fi
#120605 Omit certain /dev subdir content and modem components loaded from firmware tarballs...
#120721 avoid wildcards option introduded in 120605 (thanks to majorfoo ), remove /usr/share/icons/hicolor/icon-theme.cache
[ -d /dev/snd ] && DIRDEVSND="/dev/snd"
[ -d /dev/.udev ] && DIRDEVUDEV="/dev/.udev"
[ -f /usr/sbin/slmodemd ] && SLDAEMON="/usr/sbin/slmodemd"
[ -f /usr/sbin/martian_modem ] && MDAEMON="/usr/sbin/martian_modem"
[ -f /usr/bin/mwavem ] && MWDAEMON="/usr/bin/mwavem /usr/share/mwavem"
[ -f /usr/sbin/hamregistry ] && HAMREG="/usr/sbin/hamregistry"
[ -f /usr/share/icons/hicolor/icon-theme.cache ] && ICONCACHE=/usr/share/icons/hicolor/icon-theme.cache
# display terminal only for the first stage because it takes the most of time. 'squash' is a function, see above. 120512 $COPTIONS added...
squash / $WKGMNTPT/puppylivecdbuild/$PUPPYSFS ${COPTIONS} -e /etc /proc /initrd /var /tmp /archive /mnt /root /puppylivecdbuild $ANOTHER_REMOVE $DIRHOME $DIRSYS $DIRLOST /$PUPPYSFS $DIRDEVSND $DIRDEVUDEV $SLDAEMON $MDAEMON $MWDAEMON $HAMREG $ICONCACHE #120605 end #120721 avoid wildecards option, icon-theme.cache
sync

#add pristine folders (out of current puppy.sfs)...
mksquashfs /initrd${PUP_LAYER}/proc $WKGMNTPT/puppylivecdbuild/$PUPPYSFS -keep-as-directory
sync
mksquashfs /initrd${PUP_LAYER}/tmp $WKGMNTPT/puppylivecdbuild/$PUPPYSFS -keep-as-directory
sync
mksquashfs /initrd${PUP_LAYER}/mnt $WKGMNTPT/puppylivecdbuild/$PUPPYSFS -keep-as-directory
sync

kill $XPID

#######START WORKING ON /root#######
rm -rf /tmp/root 2> /dev/null
#do some work on /root before add it to the squashfs...
cp -a /initrd${PUP_LAYER}/root /tmp/root #pristine /root
#copy all of my-applications/
cp -af /root/my-applications/* /tmp/root/my-applications/
#some dotpups get installed here...
cp -af /root/my-roxapps /tmp/root/ 2>/dev/null
#window manager config files...
cp -af /root/.jwmrc /tmp/root/
cp -af /root/.jwmrc-tray /tmp/root/ #v411
cp -af /root/.fvwm95rc /tmp/root/
cp -af /root/.icewm/menu /tmp/root/.icewm/
#rox desktop settings...
cp -af /root/Choices/ROX-Filer/PuppyPin /tmp/root/Choices/ROX-Filer/
cp -af /root/Choices/ROX-Filer/globicons /tmp/root/Choices/ROX-Filer/
#100117 user changes get saved here, which overrides original...
if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
 mkdir -p /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
 cp -af /root/.config/rox.sourceforge.net/ROX-Filer/globicons /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
fi
#100117 i think also save user settings...
if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/Options ];then
 mkdir -p /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
 cp -af /root/.config/rox.sourceforge.net/ROX-Filer/Options /tmp/root/.config/rox.sourceforge.net/ROX-Filer/
fi
#v411 tidy up, remove desktop drive icons...
grep -v '/root/.pup_event/drive_' /tmp/root/Choices/ROX-Filer/PuppyPin > /tmp/remaster-PuppyPin
mv -f /tmp/remaster-PuppyPin /tmp/root/Choices/ROX-Filer/PuppyPin
#this may have been modified for a different w.m...
cp -af /root/.xinitrc /tmp/root/
#also this...
[ -f /root/.xset.sh ] && cp -af /root/.xset.sh /tmp/root/

#v411 gtk theme may have been changed...
cp -af /root/.gtkrc-2.0 /tmp/root/

#v411 jwm theme may have changed...
cp -af /root/.jwm/jwm_colors /tmp/root/.jwm/
cp -af /root/.jwm/jwmrc-personal /tmp/root/.jwm/
cp -af /root/.jwm/jwmrc-personal2 /tmp/root/.jwm/
cp -af /root/.jwm/jwmrc-theme /tmp/root/.jwm/

#v411 pmount preferences...
cp -af /root/.pmountauto /tmp/root/
cp -af /root/.pmountengine /tmp/root/
cp -af /root/.pmountquit /tmp/root/
cp -af /root/.pmountsingle /tmp/root/

#TODO think need to do this for /var also...

#.packages/ .files, copy any files installed to /root...
echo -n "" > /tmp/allpkgs.files
for ONEPKG in `ls -1 /root/.packages/*.files 2>/dev/null | tr "\n" " "`
do
 for ONEFILE in `cat $ONEPKG | grep '^/root/' | tr "\n" " "`
 do
  if [ -d $ONEFILE ];then #w018
   mkdir -p /tmp$ONEFILE
  fi
  if [ -f $ONEFILE ];then #w018
   DIRNAME="`dirname $ONEFILE`"
   mkdir -p /tmp$DIRNAME
   cp -a -f $ONEFILE /tmp$DIRNAME/
  fi
 done
done

#w018...
#modify /root/.packages/ files, as all installed packages are now part of the new cd...
cp -a -f /root/.packages /tmp/root/
touch /root/.packages/user-installed-packages
cat /root/.packages/user-installed-packages >> /tmp/root/.packages/woof-installed-packages
#sort -u /tmp/root/.packages/woof-installed-packages > /tmp/woof-installed-packages-tmp #v431
#mv -f /tmp/woof-installed-packages-tmp /tmp/root/.packages/woof-installed-packages
sort -u --key=1 --field-separator="|" /tmp/root/.packages/woof-installed-packages > /tmp/woof-installed-packages-tmp #110722
mv -f /tmp/woof-installed-packages-tmp /tmp/root/.packages/woof-installed-packages
echo -n "" > /tmp/root/.packages/user-installed-packages #v431
sync #120607
rm -f /tmp/root/.packages/*.files #120607
rm -f /tmp/root/.packages/*.remove #120607

eval m_19=\"$m_19\" 
Xdialog --wrap --left --title "$m_01" --msgbox "$m_19" 0 0
sync
[ "`ls /tmp/root/.packages/*.files`" = "" ] && CLEARPKGLOG="yes" || CLEARPKGLOG="no" #120607 in case user copied entire /root to /tmp for boot disk.
mksquashfs /tmp/root $WKGMNTPT/puppylivecdbuild/$PUPPYSFS -keep-as-directory
sync
rm -rf /tmp/root
#######END WORKING ON /root#######

#######START WORKING ON /etc#######
rm -rf /tmp/etc 2> /dev/null
#do some work on /etc before add it to the .sfs...
cp -a /initrd${PUP_LAYER}/etc /tmp/etc #pristine /etc.
#maybe this has been modified...
cp -af /etc/ld.so.conf /tmp/etc/

#firmware tarballs may install these scripts... 100913 not good idea...
#cp -af /etc/init.d/* /tmp/etc/init.d/   #3.99

#.packages/ .files, copy any files installed to /etc...
echo -n "" > /tmp/allpkgs.files
for ONEPKG in `ls -1 /root/.packages/*.files 2>/dev/null | tr "\n" " "`
do
 for ONEFILE in `cat $ONEPKG | grep '^/etc/' | tr "\n" " "`
 do
  if [ -d $ONEFILE ];then #w018
   mkdir -p /tmp$ONEFILE
  fi
  if [ -f $ONEFILE ];then #w018
   DIRNAME="`dirname $ONEFILE`"
   mkdir -p /tmp$DIRNAME
   cp -a -f $ONEFILE /tmp$DIRNAME/
  fi
 done
done
sync

cp -af /etc/eventmanager /tmp/etc/ #v411

#what about settings for a particular pc?...
MSG1="$m_20"
eval m_21=\"$m_21\" 
Xdialog --wrap --left --title "$m_01" --default-no --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$m_21" 0 0
if [ $? -eq 0 ];then
 cp -af /etc/codepage /tmp/etc/
 cp -af /etc/fontmap /tmp/etc/
 cp -af /etc/keyboardtype /tmp/etc/
 cp -af /etc/keymap /tmp/etc/
 cp -af /etc/mousebuttons /tmp/etc/
 cp -af /etc/mousedevice /tmp/etc/
 cp -af /etc/videomode /tmp/etc/
 cp -af /etc/eth0mode /tmp/etc/
 cp -af /etc/eth1mode /tmp/etc/
 cp -af /etc/resolv.conf /tmp/etc/
 rm -f /tmp/etc/localtime #a symlink
 cp -af /etc/localtime /tmp/etc/
 cp -af /etc/TZ /tmp/etc/
 cp -af /etc/cdburnerdevice /tmp/etc/
 cp -af /etc/dvddevice /tmp/etc/
 cp -af /etc/modemdevice /tmp/etc/
 cp -af /etc/securetelnetrc /tmp/etc/
 cp -af /etc/modules.conf /tmp/etc/
 #cp -af /etc/modprobe.conf /tmp/etc/
 cp -af /etc/modprobe.d /tmp/etc/ #101020
 cp -af /etc/rdesktoprc /tmp/etc/
 cp -af /etc/windowmanager /tmp/etc/
 cp -af /etc/xextraoptions /tmp/etc/
 cp -af /etc/X11/xorg.conf /tmp/etc/X11
 cp -af /etc/network-wizard /tmp/etc/
 cp -af /etc/simple_network_setup/* /tmp/etc/simple_network_setup/
 MSG1="$m_22"
#else
# #v431JP remove slmodems
# rm -f /tmp/etc/init.d/*slmodem*
fi

#some files to always copy...
#cp -af /etc/Puppybackgroundcolor /tmp/etc/
cp -af /etc/Puppybackgroundpicture /tmp/etc/
#TODO: other gtk and jwm customisations.

#100913 fix id-string variable...
idPATTERN="s%^DISTRO_IDSTRING.*%DISTRO_IDSTRING='${IDSTRING}'%"
sed -i -e "$idPATTERN" /tmp/etc/DISTRO_SPECS
cp -f /tmp/etc/DISTRO_SPECS /tmp/DISTRO_SPECSupdated #keep this to put into initrd.gz.

eval m_23=\"$m_23\"
Xdialog --wrap --left  --title "$m_01" --msgbox "$m_23" 0 0

#120606 in case user just now replaced the /etc directory...
sync
if [ -f /tmp/etc/.XLOADED ];then #user replaced the /etc directory
 rm -f /tmp/etc/.XLOADED
 rm -f /tmp/etc/modules/firmware.dep.inst.*
 touch /tmp/etc/personal_settings_popup_disabled
 touch /tmp/etc/personal_data_save_disabled
fi

sync


mksquashfs /tmp/etc $WKGMNTPT/puppylivecdbuild/$PUPPYSFS -keep-as-directory
sync
rm -rf /tmp/etc
#######END WORKING ON /etc#######

#######START WORKING ON /var#######
rm -rf /tmp/var 2> /dev/null
cp -a /initrd${PUP_LAYER}/var /tmp/var #pristine var

#.packages/ .files, copy any files installed to /var...
echo -n "" > /tmp/allpkgs.files
for ONEPKG in `ls -1 /root/.packages/*.files 2>/dev/null | tr "\n" " "`
do
 for ONEFILE in `cat $ONEPKG | grep '^/var/' | tr "\n" " "`
 do
  if [ -d $ONEFILE ];then #w018
   mkdir -p /tmp$ONEFILE
  fi
  if [ -f $ONEFILE ];then #w018
   DIRNAME="`dirname $ONEFILE`"
   mkdir -p /tmp$DIRNAME
   cp -a -f $ONEFILE /tmp$DIRNAME/
  fi
 done
done
sync
[ "$CLEARPKGLOG" = "yes" ] && rm -f /tmp/var/log/packages/* #120607

sync
mksquashfs /tmp/var $WKGMNTPT/puppylivecdbuild/$PUPPYSFS -keep-as-directory
sync
rm -rf /tmp/var
#######END WORKING ON /var#######
chmod a+r $WKGMNTPT/puppylivecdbuild/* &>/dev/null
chmod a-x $WKGMNTPT/puppylivecdbuild/*.sfs &>/dev/null
fi ###### end of long skip if, cleating new sfs

if [ -f $WKGMNTPT/puppylivecdbuild/isolinux.cfg ]; then
 #edit isolinux.cfg...
 ISOLINUXCFG="`cat $WKGMNTPT/puppylivecdbuild/isolinux.cfg`"
 #small tweaks, like acpi=on, ide=nodma...
 eval m_24=\"$m_24\"
 Xdialog --wrap --left  --title "$m_01" --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$m_24" 0 0
 if [ $? -eq 0 ];then
  defaulttexteditor $WKGMNTPT/puppylivecdbuild/isolinux.cfg
 fi
 sync
fi

eval m_25=\"$m_25\"
Xdialog --wrap --left  --title "$m_01" --msgbox "$m_25" 0 0
sync

BOOTPARM=""
[ -f $WKGMNTPT/puppylivecdbuild/grldr ] && BOOTPARM="-b grldr"
[ -f $WKGMNTPT/puppylivecdbuild/isolinux.bin ] && BOOTPARM="-b isolinux.bin -c boot.cat"
if [ "$BOOTPARM" = "" ]; then
eval m_25_1=\"$m_25_1\"
  Xdialog --wrap --left  --title "$m_01" --msgbox "$m_25_1" 0 0
  exit
fi

if [ "$NEW" = "yes" ]; then	#120628: no change id-string for reuse
#100913 append id-string. doesn't matter if already have an id-string appended...
echo -n "$IDSTRING" >> $WKGMNTPT/puppylivecdbuild/vmlinuz
[ -f $WKGMNTPT/puppylivecdbuild/$PUPPYSFS ] && echo -n "$IDSTRING" >> $WKGMNTPT/puppylivecdbuild/$PUPPYSFS
[ -f $WKGMNTPT/puppylivecdbuild/$ZDRVSFS ] && echo -n "$IDSTRING" >> $WKGMNTPT/puppylivecdbuild/$ZDRVSFS
#[ -f $WKGMNTPT/puppylivecdbuild/$DEVXSFS ] && echo -n "$IDSTRING" >> $WKGMNTPT/puppylivecdbuild/$DEVXSFS
sync

#100913 need to update file DISTRO_SPECS in initrd.gz, so init script can find puppy files...
mv -f $WKGMNTPT/puppylivecdbuild/initrd.gz /tmp #note $WKGMNTPT may be non-linux fs.
cd /tmp
gunzip initrd.gz
mkdir initrd-tree-tmp1
cd initrd-tree-tmp1
cat ../initrd | cpio -i -d -m
sync
rm -f ../initrd
cp -a -f /tmp/DISTRO_SPECSupdated ./DISTRO_SPECS #see earlier.
find . | cpio -o -H newc | gzip -9 > $WKGMNTPT/puppylivecdbuild/initrd.gz
sync
cd ..
rm -rf initrd-tree-tmp1
cd /root
fi #120628 end

#build new iso file, or direct burn to cd...
#to save space, burn direct from $WKGMNTPT/puppylivecdbuild/ to cd...
eval m_26=\"$m_26\"
Xdialog --wrap --left --title "$m_01" --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$m_26" 0 0

if [ ! $? -eq 0 ];then
 MSG="$m_28_2"
 eval m_27=\"$m_27\"
 Xdialog --wrap --left  --title "$m_01" --ok-label "$Yes_lbl" --cancel-label "$No_lbl" --yesno "$m_27" 0 0
 if [ $? -eq 0 ];then
  #cd $WKGMNTPT
  VOLI=""
  VOLI=$(Xdialog --title "$m_01" --stdout --inputbox "$m_27_1" 0 0 "$SFSBASE")
  [ "$VOLI" != "" ] && VOLI="-V $(echo "$VOLI"|tr ' ' '_')"
  # Joliet option
  rxvt -bg orange -fg black -title "$m_01" -e mkisofs -J -D -R $VOLI -o $WKGMNTPT/custom-puppy.iso $BOOTPARM -no-emul-boot -boot-load-size 4 -boot-info-table $WKGMNTPT/puppylivecdbuild/
  eval MSG=\"$m_28_1\"
 fi
 sync
 eval m_28=\"$m_28\"
 Xdialog --wrap --left  --title "$m_01" --msgbox "$MSG
 $m_28" 0 0
 exit
fi

VIRTUALCD=""
MSG="$m_34"
if [ "$BURNERDRV" = "" -o  "$(echo "$BURNERDRV" | grep 'loop')" != "" ]; then
 choice_cdd
fi

if [ "`echo "$BURNERDRV" | grep 'hd'`" != "" ];then
 DEVDEV="ATAPI:/dev/$BURNERDRV"
else
 DEVDEV="/dev/$BURNERDRV"
fi

#now for the actual burn...
eval m_29=\"$m_29\"
CDCHOICE="`Xdialog --wrap --left --stdout --title \"$m_01\" --menubox \"$m_29\" 0 0 4 CD-R \"$m_30\" DVD-R \"$m_31\"`"

echo '#!/bin/sh' > /tmp/new2cd.sh
if [ "`echo "$CDCHOICE" | grep 'DVD'`" = "" ];then
 #burn to CD...
 echo "mkisofs -D -R -quiet $BOOTPARM  -no-emul-boot -boot-load-size 4 -boot-info-table $WKGMNTPT/puppylivecdbuild/ | cdrecord -multi -tao -pad -data -v speed=4 gracetime=2 dev=$DEVDEV  -" >> /tmp/new2cd.sh
else
 echo "growisofs -speed=4 -Z /dev/$BURNERDRV -R -D -quiet $BOOTPARM -no-emul-boot -boot-load-size 4 -boot-info-table $WKGMNTPT/puppylivecdbuild/" >> /tmp/new2cd.sh
fi
echo "echo -n \"$m_32\": " >> /tmp/new2cd.sh
echo 'read nippi'  >> /tmp/new2cd.sh
chmod 755 /tmp/new2cd.sh
rxvt -bg orange -fg black -title "$m_01" -e /tmp/new2cd.sh

sync
rm -rf /puppylivecdbuild
rm -rf $WKGMNTPT/puppylivecdbuild
sync
umount /dev/$WKGPART

eject /dev/$BURNERDRV
eval m_33=\"$m_33\"
Xdialog --wrap --left --title "$m_01" --msgbox "$m_33" 0 0


####THE END######
